<?xml version="1.0" encoding="utf-8"?><Database Name="dnncommunity" EntityNamespace="Dnn.CommunityMetrics" ContextNamespace="Dnn.CommunityMetrics" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NV-PC07;Initial Catalog=dnncommunity;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Dnn.CommunityMetrics.Properties.Settings" SettingsPropertyName="dnncommunityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsSuperUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AffiliateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordResetToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PasswordResetExpiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_UserProfile" Member="UserProfiles" ThisKey="UserID" OtherKey="UserID" Type="UserProfile" />
      <Association Name="User_CommunityMetrics_UserActivity" Member="CommunityMetrics_UserActivities" ThisKey="UserID" OtherKey="user_id" Type="CommunityMetrics_UserActivity" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="ProfileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyDefinitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(3750)" CanBeNull="true" />
      <Column Name="PropertyText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Visibility" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExtendedVisibility" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Association Name="User_UserProfile" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ProfilePropertyDefinition_UserProfile" Member="ProfilePropertyDefinition" ThisKey="PropertyDefinitionID" OtherKey="PropertyDefinitionID" Type="ProfilePropertyDefinition" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProfilePropertyDefinition" Member="ProfilePropertyDefinitions">
    <Type Name="ProfilePropertyDefinition">
      <Column Name="PropertyDefinitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleDefID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PropertyCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ValidationExpression" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ViewOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DefaultVisibility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReadOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ProfilePropertyDefinition_UserProfile" Member="UserProfiles" ThisKey="PropertyDefinitionID" OtherKey="PropertyDefinitionID" Type="UserProfile" />
    </Type>
  </Table>
  <Table Name="dbo.CommunityMetrics_UserActivity" Member="CommunityMetrics_UserActivities">
    <Type Name="CommunityMetrics_UserActivity">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="activity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="created_on_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CommunityMetrics_UserActivity_CommunityMetrics_UserActivityLink" Member="CommunityMetrics_UserActivityLinks" ThisKey="id" OtherKey="user_activity_id" Type="CommunityMetrics_UserActivityLink" />
      <Association Name="User_CommunityMetrics_UserActivity" Member="User" ThisKey="user_id" OtherKey="UserID" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="CommunityMetrics_Activity_CommunityMetrics_UserActivity" Member="CommunityMetrics_Activity" ThisKey="activity_id" OtherKey="id" Type="CommunityMetrics_Activity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommunityMetrics_ActivitySetting" Member="CommunityMetrics_ActivitySettings">
    <Type Name="CommunityMetrics_ActivitySetting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="activity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="CommunityMetrics_Activity_CommunityMetrics_ActivitySetting" Member="CommunityMetrics_Activity" ThisKey="activity_id" OtherKey="id" Type="CommunityMetrics_Activity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommunityMetrics_Activity" Member="CommunityMetrics_Activities">
    <Type Name="CommunityMetrics_Activity">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="type_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="factor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="metric_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_filter" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="min_daily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="max_daily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_by_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_on_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_modified_by_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_modified_on_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CommunityMetrics_Activity_CommunityMetrics_UserActivity" Member="CommunityMetrics_UserActivities" ThisKey="id" OtherKey="activity_id" Type="CommunityMetrics_UserActivity" />
      <Association Name="CommunityMetrics_Activity_CommunityMetrics_ActivitySetting" Member="CommunityMetrics_ActivitySettings" ThisKey="id" OtherKey="activity_id" Type="CommunityMetrics_ActivitySetting" />
    </Type>
  </Table>
  <Table Name="dbo.CommunityMetrics_UserActivityLinks" Member="CommunityMetrics_UserActivityLinks">
    <Type Name="CommunityMetrics_UserActivityLink">
      <Column Name="id" AutoSync="Never" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_activity_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Column Name="href" Type="System.String" DbType="nvarchar(255)" CanBeNull="true" />
      <Association Name="CommunityMetrics_UserActivity_CommunityMetrics_UserActivityLink" Member="CommunityMetrics_UserActivity" ThisKey="user_activity_id" OtherKey="id" Type="CommunityMetrics_UserActivity" IsForeignKey="true" />
    </Type>
  </Table>
</Database>